### PR TITLE
replace function fix

### PR DESCRIPTION
**Pull request by 2pha**
String replace function would not work if the first argument was a variable, fixed that.
While I was there I added a couple of Number static functions (isInteger, isFinite).

### CODE REVIEW

**Comment by endel** [comment]
Hey @2pha, thanks for your pull-request!

I noticed that one test is failing (about `RegExp`), do you know what could it be? 

https://travis-ci.org/endel/js2php/builds/258037589

**Comment by 2pha** [comment]
Oh, sorry. Yes I know what it is.
I will fix it.

**Comment by 2pha** [comment]
Thanks for this repository, I sometimes want a class in both JS and PHP, this will come in very handy.

**Comment by endel** [comment]
Great, thanks! 🎉  @2pha

**Pull request merged**
